CREATE DATABASE IF NOT EXISTS voting_system;
USE voting_system;

CREATE TABLE IF NOT EXISTS admin (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE,
  password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS voters (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  voter_id VARCHAR(100) UNIQUE,
  name VARCHAR(255),
  password VARCHAR(255),
  voted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS candidates (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  candidate_name VARCHAR(255),
  party_name VARCHAR(255),
  votes INT DEFAULT 0
);
